"""
SDLC Optimization - Testing Engine
Phase 4: Generates test source code appended to the project in a tests/ folder.

Input:  Implementation result
Output: Test files saved to project_dir/testing/
Note:   Tests are GENERATED only, NOT executed.
"""

import os
from datetime import datetime
from typing import Dict, Any

from utils.file_writer import write_text_file, write_json_file


class TestingEngine:
    """
    Generates test scripts for both backend (pytest) and frontend (vitest)
    based on the code generated in the Implementation phase.
    Tests are written to disk but never executed.
    """

    def __init__(self, project_dir: str):
        self.project_dir = project_dir
        self.output_dir = os.path.join(project_dir, "testing")
        os.makedirs(self.output_dir, exist_ok=True)

    def execute(self, impl_result: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the Testing phase.

        Args:
            impl_result: Output from Phase 3 (Implementation).

        Returns:
            Phase result metadata.
        """
        print("[Phase 4] Testing - Starting...")

        generated_files = []

        # Generate backend tests
        backend_test_files = self._generate_backend_tests()
        generated_files.extend(backend_test_files)

        # Generate frontend tests
        frontend_test_files = self._generate_frontend_tests()
        generated_files.extend(frontend_test_files)

        # Generate test configuration
        config_files = self._generate_test_config()
        generated_files.extend(config_files)

        # Save metadata
        metadata = {
            "total_test_files": len(generated_files),
            "files": generated_files,
            "note": "Tests are generated only — not executed by the framework.",
            "generated_at": datetime.now().isoformat(),
        }
        write_json_file(self.output_dir, "testing_metadata.json", metadata)

        result = {
            "status": "completed",
            "phase": "testing",
            "output_dir": self.output_dir,
            "artifacts": generated_files + ["testing_metadata.json"],
            "metadata": metadata,
            "completed_at": datetime.now().isoformat(),
        }

        print(f"[Phase 4] Testing - Complete ({len(generated_files)} test files generated)")
        return result

    # ──────────────────────────────────────────────
    # Backend Test Generation
    # ──────────────────────────────────────────────

    def _generate_backend_tests(self) -> list:
        """Generate pytest-based backend test files."""
        backend_test_dir = os.path.join(self.output_dir, "backend")
        files = []

        # conftest.py
        conftest = '''"""
Pytest Configuration & Fixtures
Generated by SDLC Optimization Framework
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def client():
    """Create a test client for the FastAPI application."""
    # Import the app from the implementation
    # from main import app
    # return TestClient(app)
    pass


@pytest.fixture
def sample_user():
    """Sample user data for testing."""
    return {
        "name": "Test User",
        "email": "test@example.com",
    }
'''
        write_text_file(backend_test_dir, "conftest.py", conftest)
        files.append("backend/conftest.py")

        # test_api.py
        test_api = '''"""
API Endpoint Tests
Generated by SDLC Optimization Framework
"""

import pytest


class TestHealthEndpoint:
    """Tests for the health check endpoint."""

    def test_health_returns_200(self, client):
        """Health endpoint should return 200 status."""
        response = client.get("/health")
        assert response.status_code == 200

    def test_health_returns_status(self, client):
        """Health endpoint should return healthy status."""
        response = client.get("/health")
        assert response.json()["status"] == "healthy"


class TestAPIRoot:
    """Tests for the API root endpoint."""

    def test_api_root_returns_200(self, client):
        """API root should return 200 status."""
        response = client.get("/api/")
        assert response.status_code == 200

    def test_api_root_returns_message(self, client):
        """API root should return a message."""
        response = client.get("/api/")
        data = response.json()
        assert "message" in data
'''
        write_text_file(backend_test_dir, "test_api.py", test_api)
        files.append("backend/test_api.py")

        # test_models.py
        test_models = '''"""
Data Model Tests
Generated by SDLC Optimization Framework
"""

import pytest


class TestUserModel:
    """Tests for the User model."""

    def test_user_creation(self, sample_user):
        """User model should accept valid data."""
        assert sample_user["name"] == "Test User"
        assert sample_user["email"] == "test@example.com"

    def test_user_email_format(self, sample_user):
        """User email should contain @ symbol."""
        assert "@" in sample_user["email"]
'''
        write_text_file(backend_test_dir, "test_models.py", test_models)
        files.append("backend/test_models.py")

        return files

    # ──────────────────────────────────────────────
    # Frontend Test Generation
    # ──────────────────────────────────────────────

    def _generate_frontend_tests(self) -> list:
        """Generate vitest-based frontend test files."""
        frontend_test_dir = os.path.join(self.output_dir, "frontend")
        files = []

        # App.test.jsx
        app_test = """import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import App from '../src/App'

describe('App Component', () => {
  it('renders the application title', () => {
    render(<App />)
    expect(screen.getByText('Generated Application')).toBeDefined()
  })

  it('renders the subtitle', () => {
    render(<App />)
    expect(screen.getByText(/SDLC Optimization Framework/i)).toBeDefined()
  })
})
"""
        write_text_file(frontend_test_dir, "App.test.jsx", app_test)
        files.append("frontend/App.test.jsx")

        return files

    # ──────────────────────────────────────────────
    # Test Configuration
    # ──────────────────────────────────────────────

    def _generate_test_config(self) -> list:
        """Generate test runner configuration files."""
        files = []

        # pytest.ini for backend
        pytest_ini = """[pytest]
testpaths = backend
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
"""
        write_text_file(self.output_dir, "pytest.ini", pytest_ini)
        files.append("pytest.ini")

        return files
