import os
import base64
import re
import markdown
from xhtml2pdf import pisa

def convert_md_to_pdf(markdown_text: str, output_path: str) -> bool:
    """
    Converts markdown text to a styled PDF file.
    Replaces Mermaid blocks with rendered images using kroki.io prior to conversion.
    """
    # 1. Process Mermaid diagrams
    # We find ```mermaid...``` blocks and convert them to an image URL from kroki
    def mermaid_replacer(match):
        mermaid_code = match.group(1).strip()
        # Kroki requires base64 URL safe encoding of zlib payload, but for text-based fallback:
        # Instead of zlib, we can just use the public mermaid.ink which accepts base64
        b64_code = base64.urlsafe_b64encode(mermaid_code.encode('utf-8')).decode('utf-8')
        img_url = f"https://mermaid.ink/img/{b64_code}"
        return f'<div class="diagram-container"><img src="{img_url}" alt="Mermaid Diagram" /></div>'

    # Replace mermaid blocks
    processed_md = re.sub(r'```mermaid\n(.*?)\n```', mermaid_replacer, markdown_text, flags=re.DOTALL)

    # 2. Convert to HTML
    html_body = markdown.markdown(
        processed_md,
        extensions=['tables', 'fenced_code', 'toc', 'sane_lists']
    )

    # 3. Apply CSS Styling
    html_content = f"""
    <html>
    <head>
        <style>
            @page {{
                size: a4 landscape;
                margin: 2cm;
                @frame footer {{
                    -pdf-frame-content: footerContent;
                    bottom: 1cm;
                    margin-left: 2cm;
                    margin-right: 2cm;
                    height: 1cm;
                }}
            }}
            body {{
                font-family: Helvetica, Arial, sans-serif;
                font-size: 11pt;
                color: #333333;
                line-height: 1.5;
            }}
            h1, h2, h3, h4 {{
                color: #2c3e50;
                font-family: 'Arial', sans-serif;
            }}
            h1 {{ font-size: 24pt; border-bottom: 2px solid #3498db; padding-bottom: 5px; }}
            h2 {{ font-size: 18pt; margin-top: 20px; border-bottom: 1px solid #ecf0f1; padding-bottom: 3px; }}
            h3 {{ font-size: 14pt; color: #34495e; }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 15px;
                margin-bottom: 15px;
            }}
            th {{
                background-color: #f8f9fa;
                color: #2c3e50;
                font-weight: bold;
                border: 1px solid #dee2e6;
                padding: 8px;
                text-align: left;
            }}
            td {{
                border: 1px solid #dee2e6;
                padding: 8px;
            }}
            tr:nth-child(even) {{ background-color: #fbfcfc; }}
            pre {{
                background-color: #f4f6f7;
                padding: 10px;
                border-radius: 4px;
                border: 1px solid #e5e7e9;
                font-family: Courier, monospace;
                font-size: 9pt;
            }}
            code {{
                font-family: Courier, monospace;
                background-color: #f4f6f7;
                padding: 2px 4px;
                border-radius: 3px;
                color: #e74c3c;
            }}
            .diagram-container {{
                text-align: center;
                margin: 20px 0;
            }}
            .diagram-container img {{
                max-width: 100%;
            }}
        </style>
    </head>
    <body>
        {html_body}
        <div id="footerContent" style="text-align: right; font-size: 8pt; color: #7f8c8d;">
            Generated by SDLC Optimization Framework — Page <pdf:pagenumber>
        </div>
    </body>
    </html>
    """

    # 4. Generate PDF
    try:
        with open(output_path, "w+b") as result_file:
            pisa_status = pisa.CreatePDF(html_content, dest=result_file)
            
        return not pisa_status.err
    except Exception as e:
        print(f"Failed to generate PDF: {e}")
        return False
