"""
SDLC Optimization - Implementation Engine
Phase 3: Scaffolds a well-organized project source code structure.

Input:  RA result + Design result + RAG context
Output: Complete source code structure saved to project_dir/implementation/
"""

import os
from datetime import datetime
from typing import Dict, Any

from utils.file_writer import write_text_file, write_json_file


class ImplementationEngine:
    """
    Generates actual project source code files organized into
    frontend and backend directories within the implementation folder.
    """

    def __init__(self, project_dir: str):
        self.project_dir = project_dir
        self.output_dir = os.path.join(project_dir, "implementation")
        os.makedirs(self.output_dir, exist_ok=True)

    def execute(
        self,
        ra_result: Dict[str, Any],
        design_result: Dict[str, Any],
        rag_context: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Execute the Implementation phase.

        Args:
            ra_result: Output from Phase 1 (Requirement Analysis).
            design_result: Output from Phase 2 (Design).
            rag_context: Context from the RAG pipeline.

        Returns:
            Phase result metadata.
        """
        print("[Phase 3] Implementation - Starting...")

        generated_files = []

        # Generate backend code
        backend_files = self._generate_backend()
        generated_files.extend(backend_files)

        # Generate frontend code
        frontend_files = self._generate_frontend()
        generated_files.extend(frontend_files)

        # Generate shared configuration files
        config_files = self._generate_config_files()
        generated_files.extend(config_files)

        # Save metadata
        metadata = {
            "total_files_generated": len(generated_files),
            "files": generated_files,
            "generated_at": datetime.now().isoformat(),
        }
        write_json_file(self.output_dir, "implementation_metadata.json", metadata)

        result = {
            "status": "completed",
            "phase": "implementation",
            "output_dir": self.output_dir,
            "artifacts": generated_files + ["implementation_metadata.json"],
            "metadata": metadata,
            "completed_at": datetime.now().isoformat(),
        }

        print(f"[Phase 3] Implementation - Complete ({len(generated_files)} files generated)")
        return result

    # ──────────────────────────────────────────────
    # Backend Code Generation
    # (To be enhanced with LLM-driven generation)
    # ──────────────────────────────────────────────

    def _generate_backend(self) -> list:
        """Generate backend source code files."""
        backend_dir = os.path.join(self.output_dir, "backend")
        files = []

        # main.py - Application entry point
        main_py = '''"""
Application Entry Point
Generated by SDLC Optimization Framework
"""

from fastapi import FastAPI
from app.routes import router

app = FastAPI(
    title="Generated Application",
    version="1.0.0",
)

app.include_router(router, prefix="/api")


@app.get("/health")
async def health_check():
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''
        write_text_file(backend_dir, "main.py", main_py)
        files.append("backend/main.py")

        # models.py - Data models
        models_py = '''"""
Data Models
Generated by SDLC Optimization Framework
"""

from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class BaseEntity(BaseModel):
    id: Optional[int] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class User(BaseEntity):
    name: str
    email: str


class Project(BaseEntity):
    name: str
    description: Optional[str] = None
    owner_id: int
'''
        write_text_file(backend_dir, "models.py", models_py)
        files.append("backend/models.py")

        # routes.py - API routes
        routes_py = '''"""
API Routes
Generated by SDLC Optimization Framework
"""

from fastapi import APIRouter

router = APIRouter()


@router.get("/")
async def root():
    return {"message": "API is running"}
'''
        write_text_file(os.path.join(backend_dir, "app"), "routes.py", routes_py)
        files.append("backend/app/routes.py")

        # app/__init__.py
        write_text_file(os.path.join(backend_dir, "app"), "__init__.py", "")
        files.append("backend/app/__init__.py")

        # config.py
        config_py = '''"""
Configuration
Generated by SDLC Optimization Framework
"""

import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./app.db")
SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-production")
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
'''
        write_text_file(backend_dir, "config.py", config_py)
        files.append("backend/config.py")

        # requirements.txt
        requirements = """fastapi==0.109.0
uvicorn[standard]==0.27.0
pydantic==2.6.0
python-dotenv==1.0.1
sqlalchemy==2.0.25
"""
        write_text_file(backend_dir, "requirements.txt", requirements)
        files.append("backend/requirements.txt")

        # .env.example
        env_example = """DATABASE_URL=sqlite:///./app.db
SECRET_KEY=change-me-in-production
DEBUG=True
"""
        write_text_file(backend_dir, ".env.example", env_example)
        files.append("backend/.env.example")

        return files

    # ──────────────────────────────────────────────
    # Frontend Code Generation
    # (To be enhanced with LLM-driven generation)
    # ──────────────────────────────────────────────

    def _generate_frontend(self) -> list:
        """Generate frontend source code files."""
        frontend_dir = os.path.join(self.output_dir, "frontend")
        files = []

        # package.json
        package_json = """{
  "name": "generated-app",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.1.0",
    "tailwindcss": "^4.0.0",
    "autoprefixer": "^10.4.17"
  }
}
"""
        write_text_file(frontend_dir, "package.json", package_json)
        files.append("frontend/package.json")

        # index.html
        index_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated Application</title>
</head>
<body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
</body>
</html>
"""
        write_text_file(frontend_dir, "index.html", index_html)
        files.append("frontend/index.html")

        # src/main.jsx
        main_jsx = """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
"""
        write_text_file(os.path.join(frontend_dir, "src"), "main.jsx", main_jsx)
        files.append("frontend/src/main.jsx")

        # src/App.jsx
        app_jsx = """import React from 'react'

function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900">
          Generated Application
        </h1>
        <p className="mt-4 text-lg text-gray-600">
          Built with SDLC Optimization Framework
        </p>
      </div>
    </div>
  )
}

export default App
"""
        write_text_file(os.path.join(frontend_dir, "src"), "App.jsx", app_jsx)
        files.append("frontend/src/App.jsx")

        # src/index.css
        index_css = """@import "tailwindcss";
"""
        write_text_file(os.path.join(frontend_dir, "src"), "index.css", index_css)
        files.append("frontend/src/index.css")

        return files

    # ──────────────────────────────────────────────
    # Shared Configuration Files
    # ──────────────────────────────────────────────

    def _generate_config_files(self) -> list:
        """Generate shared project configuration files."""
        files = []

        # Root README
        readme = """# Generated Project

This project was scaffolded by the **SDLC Optimization Framework**.

## Structure

```
├── backend/       # FastAPI backend
├── frontend/      # React + Vite frontend
├── tests/         # Test suite (see testing phase)
└── deployment/    # Docker & CI/CD (see deployment phase)
```

## Getting Started

### Backend
```bash
cd backend
pip install -r requirements.txt
python main.py
```

### Frontend
```bash
cd frontend
npm install
npm run dev
```
"""
        write_text_file(self.output_dir, "README.md", readme)
        files.append("README.md")

        # .gitignore
        gitignore = """node_modules/
__pycache__/
*.pyc
.env
venv/
dist/
build/
.vite/
"""
        write_text_file(self.output_dir, ".gitignore", gitignore)
        files.append(".gitignore")

        return files
