"""
SDLC Optimization - Deployment Engine
Phase 5: Generates deployment source code appended to the project in a deployment/ folder.

Input:  Implementation result
Output: Dockerfiles, docker-compose, CI/CD pipelines saved to project_dir/deployment/
"""

import os
from datetime import datetime
from typing import Dict, Any

from utils.file_writer import write_text_file, write_json_file


class DeploymentEngine:
    """
    Generates deployment infrastructure code:
      - Dockerfiles (backend + frontend)
      - docker-compose.yml
      - GitHub Actions CI/CD pipeline
      - Nginx reverse proxy config
    """

    def __init__(self, project_dir: str):
        self.project_dir = project_dir
        self.output_dir = os.path.join(project_dir, "deployment")
        os.makedirs(self.output_dir, exist_ok=True)

    def execute(self, impl_result: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the Deployment phase.

        Args:
            impl_result: Output from Phase 3 (Implementation).

        Returns:
            Phase result metadata.
        """
        print("[Phase 5] Deployment - Starting...")

        generated_files = []

        # Docker files
        docker_files = self._generate_docker_files()
        generated_files.extend(docker_files)

        # CI/CD pipeline
        cicd_files = self._generate_cicd_pipeline()
        generated_files.extend(cicd_files)

        # Nginx config
        nginx_files = self._generate_nginx_config()
        generated_files.extend(nginx_files)

        # Save metadata
        metadata = {
            "total_deployment_files": len(generated_files),
            "files": generated_files,
            "generated_at": datetime.now().isoformat(),
        }
        write_json_file(self.output_dir, "deployment_metadata.json", metadata)

        result = {
            "status": "completed",
            "phase": "deployment",
            "output_dir": self.output_dir,
            "artifacts": generated_files + ["deployment_metadata.json"],
            "metadata": metadata,
            "completed_at": datetime.now().isoformat(),
        }

        print(f"[Phase 5] Deployment - Complete ({len(generated_files)} files generated)")
        return result

    # ──────────────────────────────────────────────
    # Docker Files
    # ──────────────────────────────────────────────

    def _generate_docker_files(self) -> list:
        """Generate Docker configuration files."""
        files = []

        # Backend Dockerfile
        backend_dockerfile = """# Backend Dockerfile
# Generated by SDLC Optimization Framework

FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
        write_text_file(self.output_dir, "Dockerfile.backend", backend_dockerfile)
        files.append("Dockerfile.backend")

        # Frontend Dockerfile
        frontend_dockerfile = """# Frontend Dockerfile
# Generated by SDLC Optimization Framework

FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
"""
        write_text_file(self.output_dir, "Dockerfile.frontend", frontend_dockerfile)
        files.append("Dockerfile.frontend")

        # docker-compose.yml
        docker_compose = """# Docker Compose Configuration
# Generated by SDLC Optimization Framework

version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
      - SECRET_KEY=change-me-in-production
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
"""
        write_text_file(self.output_dir, "docker-compose.yml", docker_compose)
        files.append("docker-compose.yml")

        return files

    # ──────────────────────────────────────────────
    # CI/CD Pipeline
    # ──────────────────────────────────────────────

    def _generate_cicd_pipeline(self) -> list:
        """Generate GitHub Actions CI/CD pipeline."""
        files = []

        github_actions_dir = os.path.join(self.output_dir, ".github", "workflows")

        ci_pipeline = """# CI/CD Pipeline
# Generated by SDLC Optimization Framework

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd implementation/backend
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd testing
          pytest backend/ -v

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd implementation/frontend
          npm ci

      - name: Run tests
        run: |
          cd implementation/frontend
          npm test

  build-and-deploy:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          cd deployment
          docker compose build

      - name: Deploy
        run: |
          echo "Deploying to production..."
          # Add deployment commands here
"""
        write_text_file(github_actions_dir, "ci-cd.yml", ci_pipeline)
        files.append(".github/workflows/ci-cd.yml")

        return files

    # ──────────────────────────────────────────────
    # Nginx Configuration
    # ──────────────────────────────────────────────

    def _generate_nginx_config(self) -> list:
        """Generate Nginx reverse proxy configuration."""
        files = []

        nginx_conf = """# Nginx Configuration
# Generated by SDLC Optimization Framework

server {
    listen 80;
    server_name localhost;

    # Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API proxy
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
"""
        write_text_file(self.output_dir, "nginx.conf", nginx_conf)
        files.append("nginx.conf")

        return files
